// genfixtures prints cross-language crypto fixtures used by the Swift
// HealthBridgeKit tests. Run with `go run ./internal/crypto/genfixtures`
// from cli/ when the protocol changes; copy the output into
// ios/Tests/HealthBridgeKitTests/CrossLanguageCryptoTests.swift.
//
// All inputs are deterministic so the output is stable across runs.
package main

import (
	"encoding/hex"
	"fmt"

	"github.com/shuyangli/healthbridge/cli/internal/crypto"
)

func main() {
	// Two deterministic "key pairs" — we use the RFC 7748 §6.1 vector for
	// the iOS side and a constant 0xbb..0xbb seed for the CLI side.
	iosPriv, _ := hex.DecodeString("77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")
	cliPriv, _ := hex.DecodeString("5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")

	iosPub, _ := crypto.SharedSecret(iosPriv, basepoint())
	cliPub, _ := crypto.SharedSecret(cliPriv, basepoint())
	shared, _ := crypto.SharedSecret(iosPriv, cliPub)
	pairID := "01J9ZX0PAIR000000000000001"

	transcript := crypto.BuildTranscript(pairID, iosPub, cliPub)
	sessionKey, _ := crypto.DeriveSessionKey(shared, transcript, "healthbridge/m2/session")
	sas := crypto.SAS(shared, transcript)

	plaintext := []byte(`{"hello":"world"}`)
	aad := []byte("pair=" + pairID + "|job=fixture|kind=read")
	fixedNonce := make([]byte, crypto.NonceSize)
	for i := range fixedNonce {
		fixedNonce[i] = byte(i + 1)
	}
	sealed, _ := crypto.SealWithNonce(sessionKey, fixedNonce, plaintext, aad)

	fmt.Printf("// auto-generated by `go run ./internal/crypto/genfixtures`\n\n")
	fmt.Printf("ios_priv  = %s\n", hex.EncodeToString(iosPriv))
	fmt.Printf("ios_pub   = %s\n", hex.EncodeToString(iosPub))
	fmt.Printf("cli_priv  = %s\n", hex.EncodeToString(cliPriv))
	fmt.Printf("cli_pub   = %s\n", hex.EncodeToString(cliPub))
	fmt.Printf("shared    = %s\n", hex.EncodeToString(shared))
	fmt.Printf("transcript= %s\n", hex.EncodeToString(transcript))
	fmt.Printf("session   = %s\n", hex.EncodeToString(sessionKey))
	fmt.Printf("sas       = %s\n", sas)
	fmt.Printf("plaintext = %s\n", hex.EncodeToString(plaintext))
	fmt.Printf("aad       = %s\n", hex.EncodeToString(aad))
	fmt.Printf("nonce     = %s\n", hex.EncodeToString(fixedNonce))
	fmt.Printf("sealed    = %s\n", hex.EncodeToString(sealed))
}

func basepoint() []byte {
	bp := make([]byte, 32)
	bp[0] = 9
	return bp
}
