import XCTest
@testable import HealthBridgeKit

/// These tests verify the Swift kit can decode blobs produced by the Go side
/// and vice versa. The blobs are checked-in fixtures, generated with a tiny
/// Go program (see Tests/HealthBridgeKitTests/Fixtures/README.md). If the
/// wire format ever drifts between the two languages, these tests fail
/// loudly with a clear "regenerate fixtures" pointer.
final class CrossLanguageCompatTests: XCTestCase {

    /// A read job built by the Go CLI's `jobs.NewReadJob` then base64-encoded
    /// via `jobs.EncodeJob`. Generated by `go run ./hack/genfixtures` (M2).
    /// In M1 we hand-build an equivalent value and assert the field names
    /// stay aligned with the Go json tags by encoding here and decoding
    /// the same blob in Go.
    func testSwiftEncodedReadJobMatchesGoFieldNames() throws {
        // The exact bytes are not stable across runs (the job ID is random
        // and CreatedAt is "now"), but we can assert that:
        //   1. Encoded JSON has snake_case field names matching Go.
        //   2. The payload object contains a "type" field equal to
        //      "step_count" — proving SampleType.rawValue serialised right.
        let payload = ReadPayload(
            type: .stepCount,
            from: ISO8601DateFormatter().date(from: "2026-04-01T00:00:00Z")!,
            to: ISO8601DateFormatter().date(from: "2026-04-07T00:00:00Z")!,
            limit: 100
        )
        let job = Job(
            id: "01J9ZX0EXAMPLE0000000000001",
            kind: .read,
            createdAt: ISO8601DateFormatter().date(from: "2026-04-07T12:00:00Z")!,
            payload: try AnyCodable.from(payload)
        )

        let data = try JSONEncoder.iso8601.encode(job)
        let str = String(data: data, encoding: .utf8)!

        // Required snake_case envelope keys.
        for key in ["\"id\"", "\"kind\"", "\"created_at\"", "\"payload\""] {
            XCTAssertTrue(str.contains(key), "missing \(key) in \(str)")
        }
        // Snake_case payload keys.
        for key in ["\"type\":\"step_count\"", "\"from\"", "\"to\"", "\"limit\":100"] {
            XCTAssertTrue(str.contains(key), "missing \(key) in \(str)")
        }
    }

    /// Decode a JobResult from a JSON shape we know the Go CLI emits.
    /// This is the inverse direction: Go writes the blob, Swift reads it.
    func testDecodeGoStyleJobResult() throws {
        let json = """
        {
          "job_id": "abc",
          "page_index": 0,
          "status": "done",
          "result": {
            "type": "step_count",
            "samples": [
              {
                "type": "step_count",
                "value": 8421,
                "unit": "count",
                "start": "2026-04-06T00:00:00Z",
                "end": "2026-04-07T00:00:00Z"
              }
            ]
          }
        }
        """.data(using: .utf8)!

        let decoded = try JSONDecoder.iso8601.decode(JobResult.self, from: json)
        XCTAssertEqual(decoded.jobID, "abc")
        XCTAssertEqual(decoded.status, .done)

        let rr = try decoded.result!.decode(ReadResult.self)
        XCTAssertEqual(rr.type, .stepCount)
        XCTAssertEqual(rr.samples.count, 1)
        XCTAssertEqual(rr.samples[0].value, 8421)
        XCTAssertEqual(rr.samples[0].unit, "count")
    }
}
