import XCTest
import CryptoKit
@testable import HealthBridgeKit

/// Cross-language crypto fixtures generated by the Go side. The point of
/// these tests is to lock in byte-for-byte interop between
/// cli/internal/crypto (Go) and Sources/HealthBridgeKit/Crypto.swift
/// (Swift). If they fail, the protocol has drifted on one side and you
/// need to either roll the change back or regenerate the fixtures via
/// `cd cli && go run ./internal/crypto/genfixtures`.
final class CrossLanguageCryptoTests: XCTestCase {

    // MARK: - Fixtures (auto-generated; do not edit by hand)

    static let iosPriv = Data(hex: "77076d0a7318a57d3c16c17251b26645df4c2f87ebc0992ab177fba51db92c2a")!
    static let iosPub  = Data(hex: "8520f0098930a754748b7ddcb43ef75a0dbf3a0d26381af4eba4a98eaa9b4e6a")!
    static let cliPriv = Data(hex: "5dab087e624a8a4b79e17f8b83800ee66f3bb1292618b6fd1c2f8b27ff88e0eb")!
    static let cliPub  = Data(hex: "de9edb7d7b7dc1b4d35b61c2ece435373f8343c85b78674dadfc7e146f882b4f")!
    static let expectedShared = Data(hex: "4a5d9d5ba4ce2de1728e3bf480350f25e07e21c947d19e3376f09b3c1e161742")!
    static let expectedSession = Data(hex: "e35975af55cdf7e685711c26ae14bf019c6700845a658f23eb7be6063f3549ed")!
    static let expectedSAS = "073900"
    static let pairID = "01J9ZX0PAIR000000000000001"
    static let plaintext = Data(hex: "7b2268656c6c6f223a22776f726c64227d")! // {"hello":"world"}
    static let aad = Data(hex: "706169723d30314a395a5830504149523030303030303030303030303030317c6a6f623d666978747572657c6b696e643d72656164")!
    static let fixedNonce = Data(hex: "0102030405060708090a0b0c")!
    static let expectedSealed = Data(hex: "0102030405060708090a0b0caecd6b0a3ac050b37b9e593eafd44a819ef656734abe8f831d02141acf62de0429")!

    // MARK: - Tests

    func testSharedSecretMatchesGoFixture() throws {
        let shared = try HealthBridgeCrypto.sharedSecret(myPriv: Self.iosPriv, theirPub: Self.cliPub)
        XCTAssertEqual(shared, Self.expectedShared)
    }

    func testTranscriptIsByteIdenticalAcrossLanguages() {
        let transcript = HealthBridgeCrypto.buildTranscript(
            pairID: Self.pairID,
            iosPub: Self.iosPub,
            cliPub: Self.cliPub
        )
        // Constant prefix is "healthbridge-pair-v1" = 20 bytes,
        // pair_id is 26 bytes, two pubkeys are 32 bytes each.
        XCTAssertEqual(transcript.count, 20 + 26 + 32 + 32)
    }

    func testSessionKeyDerivedFromSharedSecretMatchesGo() throws {
        let shared = try HealthBridgeCrypto.sharedSecret(myPriv: Self.iosPriv, theirPub: Self.cliPub)
        let transcript = HealthBridgeCrypto.buildTranscript(
            pairID: Self.pairID,
            iosPub: Self.iosPub,
            cliPub: Self.cliPub
        )
        let key = HealthBridgeCrypto.deriveSessionKey(
            shared: shared,
            transcript: transcript,
            info: "healthbridge/m2/session"
        )
        let raw = key.withUnsafeBytes { Data($0) }
        XCTAssertEqual(raw, Self.expectedSession)
    }

    func testSASMatchesGoFixture() throws {
        let shared = try HealthBridgeCrypto.sharedSecret(myPriv: Self.iosPriv, theirPub: Self.cliPub)
        let transcript = HealthBridgeCrypto.buildTranscript(
            pairID: Self.pairID,
            iosPub: Self.iosPub,
            cliPub: Self.cliPub
        )
        let sas = HealthBridgeCrypto.sas(shared: shared, transcript: transcript)
        XCTAssertEqual(sas, Self.expectedSAS)
    }

    func testSwiftCanDecryptGoSealedBlob() throws {
        let shared = try HealthBridgeCrypto.sharedSecret(myPriv: Self.iosPriv, theirPub: Self.cliPub)
        let transcript = HealthBridgeCrypto.buildTranscript(
            pairID: Self.pairID,
            iosPub: Self.iosPub,
            cliPub: Self.cliPub
        )
        let key = HealthBridgeCrypto.deriveSessionKey(
            shared: shared, transcript: transcript, info: "healthbridge/m2/session"
        )
        let opened = try HealthBridgeCrypto.open(key: key, sealed: Self.expectedSealed, aad: Self.aad)
        XCTAssertEqual(opened, Self.plaintext)
    }

    func testSwiftSealsToSameBytesAsGoWithSameNonce() throws {
        let shared = try HealthBridgeCrypto.sharedSecret(myPriv: Self.iosPriv, theirPub: Self.cliPub)
        let transcript = HealthBridgeCrypto.buildTranscript(
            pairID: Self.pairID,
            iosPub: Self.iosPub,
            cliPub: Self.cliPub
        )
        let key = HealthBridgeCrypto.deriveSessionKey(
            shared: shared, transcript: transcript, info: "healthbridge/m2/session"
        )
        let sealed = try HealthBridgeCrypto.sealWithNonce(
            key: key, nonce: Self.fixedNonce, plaintext: Self.plaintext, aad: Self.aad
        )
        XCTAssertEqual(sealed, Self.expectedSealed)
    }

    func testTamperedSealedBytesAreRejected() throws {
        let shared = try HealthBridgeCrypto.sharedSecret(myPriv: Self.iosPriv, theirPub: Self.cliPub)
        let transcript = HealthBridgeCrypto.buildTranscript(
            pairID: Self.pairID,
            iosPub: Self.iosPub,
            cliPub: Self.cliPub
        )
        let key = HealthBridgeCrypto.deriveSessionKey(
            shared: shared, transcript: transcript, info: "healthbridge/m2/session"
        )
        var tampered = Self.expectedSealed
        tampered[HealthBridgeCrypto.nonceSize + 1] ^= 0x01
        XCTAssertThrowsError(try HealthBridgeCrypto.open(key: key, sealed: tampered, aad: Self.aad))
    }
}

// MARK: - Hex helper

private extension Data {
    init?(hex: String) {
        let chars = Array(hex)
        guard chars.count % 2 == 0 else { return nil }
        var data = Data(capacity: chars.count / 2)
        var i = 0
        while i < chars.count {
            guard let high = chars[i].hexDigitValue, let low = chars[i + 1].hexDigitValue else {
                return nil
            }
            data.append(UInt8(high * 16 + low))
            i += 2
        }
        self = data
    }
}
